In [1]:
import os

os.environ['CUDA_VISIBLE_DEVICES'] = '-1' # disable cuda

In [2]:
import sys
sys.path.append('../src');

filename='../dataset/filename463.jpg'
#filename='../dataset/test.jpg'

In [3]:
import OpenPifPafTools.OpenPifPafAnnotations as opp
import OpenPifPafTools.OpenPifPafGetData as oppgd

annotation, pil_im=opp.get_openpifpaf_annotation_from_imgpath(filename)


In [4]:
print(type(pil_im))
print(type(annotation))
print(type(annotation[0]))
print(type(annotation[0].data))

for annot in annotation: 
    print(" ")
    annot.suppress_score_index=True;
    print("annot.suppress_score_index:",annot.suppress_score_index)
    print("annot.skeleton:",annot.skeleton)
    print("annot.keypoints:",annot.keypoints)
    print("len",len(annot.keypoints))
    print("between_eyes_distance:",oppgd.get_between_eyes_distance(annot.data))
    print("mean_nose_eye_distance",oppgd.get_mean_nose_eye_distance(annot.data))
    


<class 'PIL.Image.Image'>
<class 'list'>
<class 'openpifpaf.annotation.Annotation'>
<class 'numpy.ndarray'>
 
annot.suppress_score_index: True
annot.skeleton: [(16, 14), (14, 12), (17, 15), (15, 13), (12, 13), (6, 12), (7, 13), (6, 7), (6, 8), (7, 9), (8, 10), (9, 11), (2, 3), (1, 2), (1, 3), (2, 4), (3, 5), (4, 6), (5, 7)]
annot.keypoints: ['nose', 'left_eye', 'right_eye', 'left_ear', 'right_ear', 'left_shoulder', 'right_shoulder', 'left_elbow', 'right_elbow', 'left_wrist', 'right_wrist', 'left_hip', 'right_hip', 'left_knee', 'right_knee', 'left_ankle', 'right_ankle']
len 17
between_eyes_distance: 12.42884966562089
mean_nose_eye_distance 8.601227295010414
 
annot.suppress_score_index: True
annot.skeleton: [(16, 14), (14, 12), (17, 15), (15, 13), (12, 13), (6, 12), (7, 13), (6, 7), (6, 8), (7, 9), (8, 10), (9, 11), (2, 3), (1, 2), (1, 3), (2, 4), (3, 5), (4, 6), (5, 7)]
annot.keypoints: ['nose', 'left_eye', 'right_eye', 'left_ear', 'right_ear', 'left_shoulder', 'right_shoulder', 'left_

In [5]:
import os
outdir='output';
if not os.path.exists(outdir):
    os.makedirs(outdir)

In [6]:

n=0;
for annot in annotation: 
    print('')
    tupla=oppgd.get_face_bounding_rectangle(annot.data)
    pil_im_crop = pil_im.crop(tupla);
    fpath=os.path.join(outdir,"output_file_face"+str(n)+".png");
    pil_im_crop.save(fpath);
    print(tupla)
    print(fpath)
    
    print('')
    tupla=oppgd.get_body_bounding_rectangle(annot.data,factor=1.2);
    pil_im_crop = pil_im.crop(tupla);
    fpath=os.path.join(outdir,"output_file_body"+str(n)+".png");
    pil_im_crop.save(fpath);
    print(tupla)
    print(fpath)

    
    n=n+1;


(106.42378005585148, 3.640861125380656, 147.2190849343829, 50.508747486679894)
output/output_file_face0.png

(87.50062107086183, 0.0, 160.80302280426025, 151.00046908855438)
output/output_file_body0.png

(143.29539631784482, 19.742269526520527, 193.9913010698505, 72.69242667098924)
output/output_file_face1.png

(136.15382461799732, 7.370372843539627, 225.7403524545523, 147.3507248511681)
output/output_file_body1.png


In [7]:
annotation,pil_im=opp.resize_openpifpaf_annotation_and_pil_img(annotation,pil_im, width=256);
print(pil_im.size)

(256, 162)


In [8]:
fpath=os.path.join(outdir,"output_file.png");

opp.save_openpifpaf_annotation_in_img(pil_im,annotation,fpath)

In [9]:
import OpenPifPafTools.RoiDetector as opprd

det=opprd.Detector(checkpoint='shufflenetv2k16');

In [10]:
annotation, pil_im=opp.get_openpifpaf_annotation_from_imgpath(filename)

skel_vec, body_roi, face_roi = det.process_image(pil_im);

[[125.92436     31.130264     0.9602357 ]
 [132.82014     26.001753     0.9987145 ]
 [120.48786     24.455435     0.95938766]
 [141.7775      28.707481     0.963772  ]
 [113.0973      25.079088     0.87108845]
 [154.69366     59.527946     0.91484636]
 [ 98.61627     54.289253     0.9340971 ]
 [153.9618     106.09914      0.8557393 ]
 [ 93.60833     96.039505     0.95062757]
 [126.27559    122.58019      0.85561967]
 [101.75818    121.18975      0.90374035]
 [140.42918    131.77774      0.85063255]
 [105.297134   132.07954      0.9294359 ]
 [123.959785   137.82257      0.7855463 ]
 [ -4.          -4.           0.        ]
 [ -4.          -4.           0.        ]
 [ -4.          -4.           0.        ]]
[[165.7284      52.913177     0.9867906 ]
 [168.71829     43.817535     0.998814  ]
 [158.91574     49.429832     0.90470475]
 [181.21097     38.708847     0.9409672 ]
 [ -4.          -4.           0.        ]
 [207.38672     70.28643      0.9501606 ]
 [164.02135     76.43556      0.9

In [11]:
print(skel_vec)

[165.7284      52.913177     0.9867906  168.71829     43.817535
   0.998814   158.91574     49.429832     0.90470475 181.21097
  38.708847     0.9409672    0.           0.           0.
 207.38672     70.28643      0.9501606  164.02135     76.43556
   0.9227073  197.23677    113.89617      0.7799048  166.40344
 116.01859      0.5051367    0.           0.           0.
   0.           0.           0.         217.95084    135.8981
   0.86345094 183.36449    136.39256      0.747532   178.81862
 134.59128      0.8108233    0.           0.           0.
   0.           0.           0.           0.           0.
   0.        ]
